version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    environment:
      - GENERIC_TIMEZONE= # set it by your server location
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://example.com/ # set your domain name
      - WEBHOOK_URL=https://n8n.ninine.ru/
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_WORKER_SERVER_ADDRESS=0.0.0.0
      - N8N_SECURE_COOKIE=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_HEADERS_CROSS_ORIGIN_OPENER_POLICY=
      - N8N_HEADERS_CROSS_ORIGIN_EMBEDDER_POLICY=
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - n8n-network

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - n8n-network

  ssl-companion:
    image: nginxproxy/acme-companion
    container_name: ssl-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=example@gmail.com  # set your email
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge
